-- ZADANIE 40 I 44

CREATE OR REPLACE PACKAGE FIRST_PACKAGE IS
    FUNCTION OBLICZ_PODATEK(PSEUDO_K KOCURY.PSEUDO%TYPE) RETURN NUMBER;
    PROCEDURE WSTAW_BANDE(NR_B BANDY.NR_BANDY%TYPE, NAZWA_B BANDY.NAZWA%TYPE, TEREN_B BANDY.TEREN%TYPE);
END FIRST_PACKAGE;

CREATE OR REPLACE PACKAGE BODY FIRST_PACKAGE IS
    FUNCTION OBLICZ_PODATEK(PSEUDO_K KOCURY.PSEUDO%TYPE) RETURN NUMBER
    IS
        PODATEK NUMBER DEFAULT 0;
        ILE NUMBER DEFAULT 0;
    BEGIN
        SELECT CEIL(0.05*(PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA, 0))) INTO PODATEK FROM KOCURY WHERE PSEUDO = PSEUDO_K;
        SELECT COUNT(*) INTO ILE FROM KOCURY WHERE SZEF = PSEUDO_K;
        IF ILE = 0 THEN
            PODATEK := PODATEK + 2;
        END IF;
        SELECT COUNT(*) INTO ILE FROM WROGOWIE_KOCUROW WHERE PSEUDO = PSEUDO_K;
        IF ILE = 0 THEN 
            PODATEK := PODATEK + 1;
        END IF;
        SELECT NVL(MYSZY_EXTRA, 0) INTO ILE FROM KOCURY WHERE PSEUDO = PSEUDO_K;
        IF ILE > 0 THEN
            PODATEK := PODATEK + 1;
        END IF;
        RETURN PODATEK;
    END;
    
    PROCEDURE WSTAW_BANDE(NR_B BANDY.NR_BANDY%TYPE, NAZWA_B BANDY.NAZWA%TYPE, TEREN_B BANDY.TEREN%TYPE) IS
        ZNALEZIONE          NUMBER;
        EXC_DUPLICATE       EXCEPTION;
        EXC_WRONG_NUMBER    EXCEPTION;
        EXC_MESSAGE         VARCHAR2(30) DEFAULT '';
    BEGIN
        IF NR_B <= 0 THEN 
            RAISE EXC_WRONG_NUMBER;
        END IF;
        SELECT COUNT(*) INTO ZNALEZIONE FROM BANDY B WHERE B.NR_BANDY = NR_B;
        IF ZNALEZIONE <> 0 THEN
            EXC_MESSAGE := EXC_MESSAGE || ' ' || NR_B || ',';
        END IF;
        SELECT COUNT(*) INTO ZNALEZIONE FROM BANDY B WHERE B.NAZWA = NAZWA_B;
        IF ZNALEZIONE <> 0 THEN
            EXC_MESSAGE := EXC_MESSAGE || ' ' || NAZWA_B || ',';
        END IF;
        SELECT COUNT(*) INTO ZNALEZIONE FROM BANDY B WHERE B.TEREN = TEREN_B;
        IF ZNALEZIONE <> 0 THEN
            EXC_MESSAGE := EXC_MESSAGE || ' ' || TEREN_B || ',';
        END IF;
        IF LENGTH(EXC_MESSAGE) > 0 THEN
            RAISE EXC_DUPLICATE;
        END IF;
        INSERT INTO BANDY(NR_BANDY, NAZWA, TEREN) VALUES(NR_B, NAZWA_B, TEREN_B);
    EXCEPTION
        WHEN EXC_DUPLICATE THEN
            DBMS_OUTPUT.PUT_LINE(TRIM(TRAILING ',' FROM EXC_MESSAGE) || ': JUZ ISTNIEJE');
        WHEN EXC_WRONG_NUMBER THEN 
            DBMS_OUTPUT.PUT_LINE('NR BANDY MUSI BYC LICZBA DODATNIA');
    END;
END FIRST_PACKAGE;


BEGIN
    FIRST_PACKAGE.WSTAW_BANDE(1, 'CZARNI RYCERZE', 'POLE');
END;


SELECT PSEUDO, PRZYDZIAL_MYSZY, FIRST_PACKAGE.OBLICZ_PODATEK(PSEUDO)
FROM KOCURY;